### ISSUE TITLE
Will the berglas provider be an official terraform provider?

### ISSUE THREAD

**Issue by tfhartmann** [sethvargo/terraform-provider-berglas#3]
Hi @sethvargo first off thanks for creating this!    I know this is a fairly new project, and I wanted to ask, do you foresee this provider every being included as an officially supported provider?

**Comment by sethvargo** [comment]
Define "officially supported"?

**Comment by tfhartmann** [comment]
> "officially supported"

Heh that may be a poor choice of words on my part.   Do you expect that I'll be able to use the provider by defining a provider block, and using `terraform init` to download and load the correct version of the provider rather then have to build the provider locally.

**Comment by sethvargo** [comment]
Probably not in the short term. I have no control over that /shrug. The official process for getting it added is time consuming and I was not successful with terraform-provider-filesystem (which arguably has a larger user base)

**Comment by tfhartmann** [comment]
understood, and thanks!

 ![bitmoji](https://render.bitstrips.com/v2/cpanel/9ab32e9a-f43b-4dd4-90f6-1c4c77b47655-755c5393-e372-44a8-9b25-54d49526172e-v1.png?transparent=1&palette=1&width=246)
