### ISSUE TITLE
Add support for Secret Manager version of Berglas 

### ISSUE THREAD

**Issue by athon-millane** [sethvargo/terraform-provider-berglas#8]
Hi @sethvargo, thanks for your great work on Berglas and this provider.

Is there any chance you could update this provider to support using Secret Manager as well as Cloud Storage?

In line with your PR [here](https://github.com/GoogleCloudPlatform/berglas/pull/89).

Thanks

**Comment by sethvargo** [comment]
Hi @athon-millane 

To use Secret Manager, use the [official Google Cloud Terraform provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret). Thanks!
